// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9qxdsCdnRTLoHZq2IOvqyLInL6F-UN10',
    appId: '1:928910294784:web:962d51bb65b34aaaacfde5',
    messagingSenderId: '928910294784',
    projectId: 'joamman-f6d7e',
    authDomain: 'joamman-f6d7e.firebaseapp.com',
    storageBucket: 'joamman-f6d7e.appspot.com',
    measurementId: 'G-Z81E13D7J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUDT-jedHZvVa6YZnXauWrP0B7JKxc_Y0',
    appId: '1:928910294784:android:7dda6d8d41bfdf82acfde5',
    messagingSenderId: '928910294784',
    projectId: 'joamman-f6d7e',
    storageBucket: 'joamman-f6d7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJubpqTj4EhVZUqx-RD6tmQ7w8VuPtsjk',
    appId: '1:928910294784:ios:fd0af6890e998accacfde5',
    messagingSenderId: '928910294784',
    projectId: 'joamman-f6d7e',
    storageBucket: 'joamman-f6d7e.appspot.com',
    androidClientId: '928910294784-s627tksvmqcbdlujfo8u1mgj26072gsh.apps.googleusercontent.com',
    iosClientId: '928910294784-7d8k204g3dlba896c7njv5qiaggi7mlp.apps.googleusercontent.com',
    iosBundleId: 'com.ghanayem.joAmman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJubpqTj4EhVZUqx-RD6tmQ7w8VuPtsjk',
    appId: '1:928910294784:ios:fd0af6890e998accacfde5',
    messagingSenderId: '928910294784',
    projectId: 'joamman-f6d7e',
    storageBucket: 'joamman-f6d7e.appspot.com',
    androidClientId: '928910294784-s627tksvmqcbdlujfo8u1mgj26072gsh.apps.googleusercontent.com',
    iosClientId: '928910294784-7d8k204g3dlba896c7njv5qiaggi7mlp.apps.googleusercontent.com',
    iosBundleId: 'com.ghanayem.joAmman',
  );
}
