const Map<String, String> ar = {
  "Jordan Orthopedic Association": "جمعية العظام الأردنية",
  "Username": "اسم المستخدم",
  "Password": "كلمة المرور",
  "Confirm password": "تأكيد كلمة المرور",
  "Sign In": "تسجيل الدخول",
  "Please try again": "يرجى المحاولة مرة أخرى",
  "Name": "الاسم",
  "Phone number": "رقم الهاتف",
  "Invalid phone number": "رقم الهاتف غير صالح",
  "Action": "الإجراء",
  "Info": "معلومات",
  "Edit": "تعديل",
  "Delete": "حذف",
  "Cancel": "إلغاء",
  "Confirm": "تأكيد",
  "Are you sure?": "هل أنت متأكد؟",
  "Email": "البريد الإلكتروني",
  "Search by country name or dial code": "البحث حسب اسم الدولة أو رمز الاتصال",
  "Submit": "إرسال",
  "Please enter valid password": "يرجى إدخال كلمة مرور صالحة",
  "Password does not match": "كلمة المرور غير متطابقة",
  "Please enter valid email": "يرجى إدخال بريد إلكتروني صالح",
  "Please enter valid phone": "يرجى إدخال رقم هاتف صالح",
  "OR": "أو",
  "Create Your Account": "إنشاء حساب",
  "Register": "تسجيل",
  "Home Address": "عنوان المنزل",
  "Work Address": "عنوان العمل",
  "Full Name": "الاسم الكامل",
  "Syndicate Number": "رقم النقابة",
  "Home": "الرئيسية",
  "Events": "الفعاليات",
  "Profile": "الملف الشخصي",
  "Welcome back": "مرحبًا بعودتك",
  "Search on Researches": "البحث في الأبحاث",
  "Doctors Research :": "أبحاث الأطباء :",
  "No items found": "لم يتم العثور على عناصر",
  "The list is currently empty.": "القائمة فارغة حاليًا.",
  "Date Publication": "تاريخ النشر",
  "PDF": "ملف بصيغة PDF",
  "Researches": "الأبحاث",
  "Expiration": "تاريخ الانتهاء",
  "Settings": "الإعدادات",
  "Edit Profile": "تعديل الملف الشخصي",
  "History": "السجل",
  "Payment": "الدفع",
  "Notifications": "الإشعارات",
  "Contact Us": "اتصل بنا",
  "Sign Out": "تسجيل الخروج",
  "Title": "العنوان",
  "Description": "الوصف",
  "Create Research": "إنشاء بحث",
  "Add PDF": "إضافة PDF",
  "Save Changes": "حفظ التغييرات",
  "Try Again": "حاول مرة أخرى",
  "Please select a file of type PDF": "يرجى تحديد ملف من نوع PDF",
  "Invalid verification code": "رمز التحقق غير صالح",
  "Verification": "التحقق",
  "Enter your OTP code number": "أدخل رمز OTP الخاص بك",
  "Please enter your OTP code number": "يرجى إدخال رمز OTP الخاص بك",
  "Verify": "التحقق",
  "Didn't you receive any code ?": "لم تتلق أي رمز؟",
  "Resend new code": "إعادة إرسال رمز جديد",
  "sec": "ثانية",
  "New Password": "كلمة مرور جديدة",
  "Forgot Password": "هل نسيت كلمة المرور",
  "Password has been changed successfully": "تم تغيير كلمة المرور بنجاح",
  "Close": "إغلاق",
  "Call": "اتصال",
  "Call the following number for assistance": "اتصل بالرقم التالي للمساعدة",
  "My Researches": "أبحاثي",
  "Edit Research": "تعديل البحث",
  "Change PDF": "تغيير PDF",
  "Launch Event": "Launch Event",
  "Status": "الحالة",
  "Doctor": "الطبيب",
  "Users": "المستخدمين",
  "Points": "النقاط",
  "Doctors": "الأطباء",
  "License Expiry": "انتهاء الرخصة",
  "Phone Number": "رقم الهاتف",
  "Image": "الصورة",
  "Delete doctor": "حذف الطبيب",
  "Delete event": "حذف الحدث",
  "Link": "الرابط",
  "Add Image": "إضافة صورة",
  "info": "معلومات",
  "add": "إضافة",
  "edit": "تعديل",
  "Delete research": "حذف البحث",
  "soon": "قريبًا",
  "Courses": "الدورات",
  "Search on Courses": "البحث عن الدورات",
  "Videos": "الفيديوهات",
  "Delete video": "حذف الفيديو",
  "Video": "الفيديو",
  "Add Video": "إضافة فيديو",
  "Change Video": "تغيير الفيديو",
  "Add Payment": "إضافة دفعة",
  "Delete course": "حذف الدورة",
  "User Pro": "مستخدم برو",
  "Event": "حدث",
  "Course": "دورة",
  "Price": "السعر",
  "Free": "مجاناً",
  "Purchased": "تم الشراء",
  "My Courses": "دوراتي",
  "Contact the supervisor by calling the following number for the purchase process": "اتصل بالمشرف عن طريق الاتصال بالرقم التالي لعملية الشراء",
  "Buy a Course": "شراء الدورة",
  "Scientific Journals": "المجلات العلمية",
  "Scientific Journals :": "المجلات العلمية :",
  "Search on Scientific Journals": "البحث في المجلات العلمية",
  "Language": "اللغة",
  "Sliders": "الشرائح",
  "Delete slider": "حذف الشريحة",
  "Forget the password?": "هل نسيت كلمة المرور؟",
  "pending": "قيد الانتظار",
  "accept": "تم القبول",
  "reject": "تم الرفض"
};
