const Map<String, String> ar = {
  "Sign In": "تسجيل الدخول",
  "Please try again": "يرجى المحاولة مرة أخرى",
  "Name": "الاسم",
  "Phone number": "رقم الهاتف",
  "Invalid phone number": "رقم الهاتف غير صالح",
  "Action": "الإجراء",
  "Info": "معلومات",
  "Edit": "تعديل",
  "Delete": "حذف",
  "Cancel": "إلغاء",
  "Confirm": "تأكيد",
  "Are you sure?": "هل أنت متأكد؟",
  "Email": "البريد الإلكتروني",
  "Search by country name or dial code": "البحث حسب اسم الدولة أو رمز الاتصال",
  "Submit": "إرسال",
  "Please enter valid password": "يرجى إدخال كلمة مرور صالحة",
  "Password does not match": "كلمة المرور غير متطابقة",
  "Please enter valid email": "يرجى إدخال بريد إلكتروني صالح",
  "Please enter valid phone": "يرجى إدخال رقم هاتف صالح",
  "No items found": "لم يتم العثور على عناصر",
  "The list is currently empty.": "القائمة فارغة حاليًا.",
  "Sign Out": "تسجيل الخروج",
  "Save Changes": "حفظ التغييرات",
  "Try Again": "حاول مرة أخرى",
  "Invalid verification code": "رمز التحقق غير صالح",
  "Verification": "التحقق",
  "Enter your OTP code number": "أدخل رمز OTP الخاص بك",
  "Please enter your OTP code number": "يرجى إدخال رمز OTP الخاص بك",
  "Verify": "التحقق",
  "Didn't you receive any code ?": "لم تتلق أي رمز؟",
  "Resend new code": "إعادة إرسال رمز جديد",
  "sec": "ثانية",
  "Close": "إغلاق",
  "Call": "اتصال",
  "Status": "الحالة",
  "Users": "المستخدمين",
  "Phone Number": "رقم الهاتف",
  "Image": "الصورة",
  "Add Image": "إضافة صورة",
  "info": "معلومات",
  "add": "إضافة",
  "edit": "تعديل",
  "Price": "السعر",
  "Language": "اللغة",
  "Config": "الاعدادات",
  "Orders": "الطلبات",
  "Sliders": "الشرائح",
  "Delete slider": "حذف الشريحة",
};
