const Map<String, String> en = {
  "Jordan Orthopedic Association": "Jordan Orthopedic Association",
  "Username": "Username",
  "Password": "Password",
  "Confirm password": "Confirm password",
  "Sign In": "Sign In",
  "Please try again": "Please try again",
  "Name": "Name",
  "Phone number": "Phone number",
  "Invalid phone number": "Invalid phone number",
  "Action": "Action",
  "Info": "Info",
  "Edit": "Edit",
  "Delete": "Delete",
  "Cancel": "Cancel",
  "Confirm": "Confirm",
  "Are you sure?": "Are you sure?",
  "Email": "Email",
  "Search by country name or dial code": "Search by country name or dial code",
  "Submit": "Submit",
  "Please enter valid password": "Please enter valid password",
  "Password does not match": "Password does not match",
  "Please enter valid email": "Please enter valid email",
  "Please enter valid phone": "Please enter valid phone",
  "OR": "OR",
  "Create Your Account": "Create Your Account",
  "Register": "Register",
  "Home Address": "Home Address",
  "Work Address": "Work Address",
  "Full Name": "Full Name",
  "Syndicate Number": "Syndicate Number",
  "Home": "Home",
  "Events": "Events",
  "Profile": "Profile",
  "Welcome back": "Welcome back",
  "Search on Researches": "Search on Researches",
  "Doctors Research :": "Doctors Research :",
  "No items found": "No items found",
  "The list is currently empty.": "The list is currently empty.",
  "Date Publication": "Date Publication",
  "PDF": "PDF",
  "Researches": "Researches",
  "Expiration": "Expiration",
  "Settings": "Settings",
  "Edit Profile": "Edit Profile",
  "History": "History",
  "Payment": "Payment",
  "Notifications": "Notifications",
  "Contact Us": "Contact Us",
  "Sign Out": "Sign Out",
  "Title": "Title",
  "Description": "Description",
  "Create Research": "Create Research",
  "Add PDF": "Add PDF",
  "Save Changes": "Save Changes",
  "Try Again": "Try Again",
  "Please select a file of type PDF": "Please select a file of type PDF",
  "Invalid verification code": "Invalid verification code",
  "Verification": "Verification",
  "Enter your OTP code number": "Enter your OTP code number",
  "Please enter your OTP code number": "Please enter your OTP code number",
  "Verify": "Verify",
  "Didn't you receive any code ?": "Didn't you receive any code ?",
  "Resend new code": "Resend new code",
  "sec": "sec",
  "New Password": "New Password",
  "Forgot Password": "Forgot Password",
  "Password has been changed successfully": "Password has been changed successfully",
  "Close": "Close",
  "Call": "Call",
  "Call the following number for assistance": "Call the following number for assistance",
  "My Researches": "My Researches",
  "Edit Research": "Edit Research",
  "Change PDF": "Change PDF",
  "Launch Event": "Launch Event",
  "Status": "Status",
  "Doctor": "Doctor",
  "Users": "Users",
  "Points": "Points",
  "Doctors": "Doctors",
  "License Expiry": "License Expiry",
  "Phone Number": "Phone Number",
  "Image": "Image",
  "Delete doctor": "Delete doctor",
  "Delete event": "Delete event",
  "Link": "Link",
  "Add Image": "Add Image",
  "info": "Info",
  "add": "Add",
  "edit": "Edit",
  "Delete research": "Delete research",
  "soon": "soon",
  "Courses": "Courses",
  "Search on Courses": "Search on Courses",
  "Videos": "Videos",
  "Delete video": "Delete video",
  "Video": "Video",
  "Add Video": "Add Video",
  "Change Video": "Change Video",
  "Add Payment": "Add Payment",
  "Delete course": "Delete course",
  "User Pro": "User Pro",
  "Event": "Event",
  "Course": "Course",
  "Price": "Price",
  "Free": "Free",
  "Purchased": "Purchased",
  "My Courses": "My Courses",
  "Contact the supervisor by calling the following number for the purchase process": "Contact the supervisor by calling the following number for the purchase process",
  "Buy a Course": "Buy a Course",
  "Scientific Journals": "Scientific Journals",
  "Scientific Journals :": "Scientific Journals :",
  "Search on Scientific Journals": "Search on Scientific Journals",
  "Language": "Language",
  "Sliders": "Sliders",
  "Delete slider": "Delete slider",
  "Forget the password?": "Forget the password?",
  "pending": "Pending",
  "accept": "Accepted",
  "reject": "Rejected",
};
